# Generated by Django 3.0.6 on 2020-05-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20200512_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='p_id',
        ),
        migrations.AddField(
            model_name='package',
            name='event_date',
            field=models.DateField(null=True),
        ),
    ]
