# Generated by Django 3.0.6 on 2020-05-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20200519_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
