# Generated by Django 3.1.1 on 2020-09-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20200521_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image_url',
        ),
    ]
