# Generated by Django 3.0.6 on 2020-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=0, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
